myapp/urls.py
from django.urls import path
app_name="myapp"
from myapp import views

urlpatterns=[
    path('img_upld/', views.img_upld,name="img_upload"),
    path('img_disp/',views.img_disp,name='img_disp'),
]

p14/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG==True:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage
# Create your views here.
def img_upld(request):
    return render(request,'img_upld.html')
def img_disp(request):
    file_url=False
    if request.method=='POST' and request.FILES:
        image= request.FILES['sam']
        fs=FileSystemStorage()
        file=fs.save(image.name,image)
        file_url= fs.url(file)
    return render(request,'img_display.html',context={'file_url':file_url})

templates/img_display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Image_Display</title>
</head>
<body>
    {% if file_url %}
    <img src="{{file_url}}" alt="NO image found" height="100" width="200">
    {% endif %}
</body>
</html>

templates/img_upld.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IMG_UPLOAD</title>
</head>
<body>
    <form action="{% url 'myapp:img_disp' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        Image:<input type="file" name="sam" id="sam">
        <input type="submit" value="submit">
    </form>
    
</body>
</html>